name: osubot-telegram

services:
  osubot:
    image: ghcr.io/airkek/osubot-telegram
    container_name: osubot_bot
    env_file: .env
    restart: always

    volumes:
      - ${OSU_BEATMAP_CACHE}:/usr/osubot/beatmap_cache
      - ${BOT_DATA_PATH}:/usr/osubot/data
      - ${TELEGRAM_API_DATA_PATH}:/var/lib/telegram-bot-api

    depends_on:
      - database
      - telegram_api

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HEALTHCHECK_APP_PORT}/health"]
      interval: 5m
      timeout: 10s
      start_period: 1m
      retries: 3

  database:
    image: timescale/timescaledb:latest-pg17
    container_name: osubot_postgres
    restart: always

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      TELEGRAM_MAX_WEBHOOK_CONNECTIONS: ${TELEGRAM_LOCAL_API_MAX_WEBHOOK_CONNECTIONS}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TIMESCALEDB_TELEMETRY: 'off'
      
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m

    command: >-
      postgres -c max_connections=1000
              -c shared_buffers=256MB
              -c effective_cache_size=768MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
              -c shared_preload_libraries='timescaledb'

  telegram_api:
    image: aiogram/telegram-bot-api:latest
    container_name: osubot_telegram_api
    restart: always

    environment:
      TELEGRAM_API_ID: ${TELEGRAM_APP_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_APP_API_HASH}
      TELEGRAM_FILTER: ${TELEGRAM_LOCAL_API_FILTER_REMAINDER}/${TELEGRAM_LOCAL_API_FILTER_MODULO}
      TELEGRAM_LOCAL: true

    volumes:
      - ${TELEGRAM_API_DATA_PATH}:/var/lib/telegram-bot-api
      - ${BOT_DATA_PATH}:/usr/osubot/data
