import { ControllableFeature } from "core/storage/ControllableFeature";
import { IChatSettings } from "core/IChatSettings";
import { IUserSettings } from "core/IUserSettings";
import { ContentOutput } from "core/ContentOutput";
import { ExternalId } from "core/ExternalId";
import { IMessageIdentity } from "core/IMessageIdentity";
import { Platform } from "core/Platform";
import { IReplyMessage } from "core/IReplyMessage";
import { ISendOptions } from "core/ISendOptions";
import { ITextLinkEntity } from "core/ITextLinkEntity";
import { ILocalizer } from "localization/ILocalizer";
import { IKeyboard } from "presentation/keyboard/IKeyboard";

export interface IMessageContext extends ILocalizer {
    readonly platform: Platform;
    readonly externalSenderId: ExternalId;
    readonly externalChatId: ExternalId;
    readonly userId: number;
    readonly chatId: number;
    readonly senderId: number;
    readonly plainText?: string;
    readonly plainPayload?: string;
    readonly replyMessage?: IReplyMessage;
    readonly isInGroupChat: boolean;
    readonly isFromOwner: boolean;
    readonly text?: string;
    readonly messagePayload?: string;

    bindIdentity(identity: IMessageIdentity): void;
    applyTextOverrides(aliases: Record<string, string>): void;
    ensureUserInfoUpdated(): Promise<void>;
    activateLocalizer(): Promise<void>;
    reactivateLocalizer(): Promise<void>;
    checkFeature(feature: ControllableFeature): Promise<boolean>;
    availableContentOutputs(): Promise<ContentOutput[]>;
    preferredContentOutput(): Promise<ContentOutput>;
    preferCardsOutput(): Promise<boolean>;
    userSettings(forceUpdate?: boolean): Promise<IUserSettings>;
    chatSettings(forceUpdate?: boolean): Promise<IChatSettings>;
    updateUserSettings(settings: IUserSettings): Promise<void>;
    updateChatSettings(settings: IChatSettings): Promise<void>;
    reply(text: string, options?: ISendOptions): Promise<unknown>;
    send(text: string, options?: ISendOptions, replyTo?: number): Promise<unknown>;
    remove(): Promise<unknown>;
    edit(text: string, options?: ISendOptions): Promise<void>;
    editMarkup(keyboard: IKeyboard): Promise<unknown>;
    answer(text: string): Promise<true | void>;
    acknowledge(): Promise<void>;
    isUserAdmin(accountId: number): Promise<boolean>;
    isSenderAdmin(): Promise<boolean>;
    isBotAdmin(): Promise<boolean>;
    isUserInChat(accountId: number, chatId?: number): Promise<boolean>;
    isChatValid(chatId: number): Promise<boolean>;
    isBotInChat(chatId: number): Promise<boolean>;
    mentionUser(accountId: number): Promise<string>;
    chatMembersCount(): Promise<number>;
    hasLinks(): boolean;
    getLinks(): ITextLinkEntity[];
    hasFile(): boolean;
    getFileName(): string;
    getFileSize(): number;
    registerTempFile(filePath: string): void;
    downloadFile(): Promise<string>;
    removeFile(): Promise<void>;
}
