name: "Build and run bot tests"

on:
  push:
    branches: [master]
    paths:
      - "bot/**"
      - "contracts/**"
      - ".github/workflows/build_and_run_bot_tests.yml"
  pull_request:
    branches: [master]
    paths:
      - "bot/**"
      - "contracts/**"
      - ".github/workflows/build_and_run_bot_tests.yml"

permissions:
  contents: read

concurrency:
  group: build-bot-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: bot/package-lock.json

      - name: Install modules
        run: npm ci

      - name: Build bot
        run: npm run build:node

      - name: Run Jest tests
        run: npm run test:js
