name: "Build and run tests"

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

permissions:
    contents: read

concurrency:
    group: build-tests-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm

            - name: Install modules
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run unit tests
              run: npm run test:run
